# Site settings
title: Big Boat
email: liu.david.ge@gmail.com
description: I'm now a U2 computer engineering student. I love JAVA,embedded-c-programming and C++.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nightelfel.github.io" # the base hostname & protocol for your site
twitter_username: NULL
github_username:  nightelfel

# Build settings
markdown: kramdown
